### ISSUE TITLE
Issues in Running Automated test because of these commented lines,

### ISSUE THREAD

**Issue by Owaiskhan9654** [siminegroup/E2EDNA2#21]
https://github.com/siminegroup/E2EDNA2/blob/e1ff77022be647d6946cbe5c3298b356a0f22904/main.py#L120
After removing run_num from the executing commands it shows  KeyError: 'run_num'
Please see the screenshot attached. @taoliu032 @InfluenceFunctional 
![image](https://github.com/siminegroup/E2EDNA2/assets/47840160/c13e7e0c-027d-4264-b967-8f72847a1286)

**Comment by taoliu032** [comment]
Yes, you caught the change -- I commented out the run_num part in argparse so that in the yaml configuration file, `run_num` can be either integer or a string. Consequently, the run directory can be either "run1" or "run1_for_ATP_system"

**Comment by taoliu032** [comment]
I will update the automated tests -- they are outdated since I have made many modifications since we published the JOSS paper

**Comment by taoliu032** [comment]
I have update the code by PR #22  so that `run_num` can be used in command line as well. Feel free to re-open this issue if you run into other problems with the tests. Thanks!
