### ISSUE TITLE
KeyError: 'predict_2dSS' in opendna.py line 281

### ISSUE THREAD

**Issue by Owaiskhan9654** [siminegroup/E2EDNA2#23]
Got 1 more bug in line 281 in opendna.py file.

![image](https://github.com/siminegroup/E2EDNA2/assets/47840160/d07df086-4179-4284-991e-42c8b04ec50e)
@taoliu032 @InfluenceFunctional

**Comment by taoliu032** [comment]
Should be solved by now, please try again and let us know any other feedback, thanks again!
