### ISSUE TITLE
Lightdock Rust nucleic support

### ISSUE THREAD

**Issue by brianjimenez** [siminegroup/E2EDNA2#5]
Dear E2DNA2 developers,

Since you are using LightDock in some parts of your pipeline, it could be of your interest the [0.2.0 release](https://github.com/lightdock/lightdock-rust/releases/tag/v0.2.0) of the Rust implementation of the framework. This new release adds support for protein-nucleic complex prediction and typically runs 5x-6x faster compared to the Python+C implementations of the Python LightDock flavor, and two orders of magnitude less amount of memory. There is more information on how to compile and use the Rust version [here](https://lightdock.org/tutorials/0.9.2/rust).

Hope it helps!

**Comment by InfluenceFunctional** [comment]
@brianjimenez Thanks for the info here. Sounds like a nice upgrade on the already quite good (from our point of view) LightDock performance. We'll definitely keep it in mind!

**Comment by brianjimenez** [comment]
Glad LightDock is helpful for your project. Please, don't hesitate to contact me if you find any problem using LightDock or you have any question.

**Comment by taoliu032** [comment]
Certainly!
