### ISSUE TITLE
Error: 'str' object is not callable; in opendna.py, line 535

### ISSUE THREAD

**Issue by schackartk** [siminegroup/E2EDNA2#6]
Hello,

I am excited to try out this tool!

I have installed all dependencies successfully (I believe), and I am running the script `automate_tests.sh`. Most tests are passing, but tests 4, 5, 7, and 8 are failing during the docking step with the same exception.

```
TESTING MODE #4: 'coarse dock'
Starting Fresh Run 4
Simulation mode: coarse dock
Simulating TAATGTTAATTG with YQTQ.pdb
Getting Secondary Structure(s)
Running over 1 possible 2D structures.
2D structure #0 is                              : .(((....))).

Folding Aptamer from Sequence. Fold speed = quick.
Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
2D structure after MMB folding (from MDAnalysis): .(((....))).
Initial fold fidelity = 1.000
Initial fold fidelity = 1.000 (from MDAnalysis)
Folded the aptamer and generated the folded structure: foldedAptamer_0.pdb

No relaxation (smoothing) of the folded aptamer.

Docking
Traceback (most recent call last):
  File "main.py", line 230, in <module>
    opendnaOutput = opendna.run()  # retrieve binding information (eventually this should become a normalized c-number)    
  File "/home/ken/personal/E2EDNA2/opendna.py", line 297, in run
    outputDict['dock scores {}'.format(self.i)] = self.dock(self.pdbDict['representative aptamer {}'.format(self.i)], self.targetPDB)  # eg, "peptide.pdb" which can be created given peptide sequence by buildPeptide in function dock
  File "/home/ken/personal/E2EDNA2/opendna.py", line 535, in dock
    ld.run()
TypeError: 'str' object is not callable
```

I am unsure what the underlying problem is, but maybe it has to do with a mistake between:

* The instance variable `run` on line 487 of instances.py: `self.run     = params['ld run']`
* The method `run()` on line 504 of instances.py: `def run(self):`

Because the instance variable from line 487 is the string value set on line 220 in main.py: `params['ld run']       = 'lightdock3.py'`. Maybe this variable is somehow shadowing the method `run()`, and so it is failing to "call" `str()` (*i.e.* `'lightdock3.py'()`)?

I would appreciate any help with resolving this.

Thank you!

**Comment by taoliu032** [comment]
👋 @schackartk - thank you very much for trying our software and spotting this issue! 

You were absolutely right, the variable `self.run` and method `run` within `ld` class were conflicting with each other. I have appended a word "Script" to the variable names to resolve the conflicts and the automated tests on my end have finished without issues. I have made a commit and you can see the updated repo here: https://github.com/siminegroup/E2EDNA2/tree/a42ba5026bcdc843b1a134c0358371a6faa454ce

Please try the tests again and let us know if the issue is gone or still persists. Thank you again!

**Comment by schackartk** [comment]
Thanks so much for the quick response and fix!

It is working now.
